#!/bin/bash
set -e

# ==============================================================================
# pull-ssm-params.sh
# Purpose: Pull variables from AWS SSM Parameter Store and generate a local .env
# Path Prefix: /ott-chat/prod/
# ==============================================================================

ENV_FILE=".env"
PATH_PREFIX="/ott-chat/prod/"
AWS_REGION=${AWS_REGION:-"us-east-1"}

echo "------------------------------------------------------------"
echo "🔐 Starting AWS SSM Parameter Store Sync..."
echo "📂 Path Prefix: $PATH_PREFIX"
echo "🌍 AWS Region: $AWS_REGION"
echo "------------------------------------------------------------"

# Initialize .env with header
echo "# ===============================================================" > $ENV_FILE
echo "# AUTO-GENERATED BY DEPLOYMENT PIPELINE ON $(date)" >> $ENV_FILE
echo "# DO NOT EDIT THIS FILE MANUALLY - SECURED VIA AWS SSM" >> $ENV_FILE
echo "# ===============================================================" >> $ENV_FILE
echo "" >> $ENV_FILE


# Temporary file to store parameters raw
TEMP_PARAMS=$(mktemp)

# Fetch variables using AWS CLI
# Requires AmazonSSMReadOnlyAccess attached to the EC2 IAM Role or Active Credentials
aws ssm get-parameters-by-path \
    --path "$PATH_PREFIX" \
    --recursive \
    --with-decryption \
    --region "$AWS_REGION" \
    --query "Parameters[*].[Name,Value]" \
    --output text > "$TEMP_PARAMS"

# Check if parameters were returned
if [ ! -s "$TEMP_PARAMS" ]; then
    echo "⚠️ Warning: No parameters found in AWS SSM under path prefix '$PATH_PREFIX'."
    echo "Please ensure you have created parameters in AWS Systems Manager Console."
    rm -f "$TEMP_PARAMS"
    exit 0
fi

# Process parameters and write to .env
while read -r name value; do
    # Remove the prefix (e.g. /ott-chat/prod/JWT_SECRET becomes JWT_SECRET)
    clean_name="${name#$PATH_PREFIX}"
    
    # Write key=value pair
    echo "$clean_name=$value" >> $ENV_FILE
    echo "✅ Synchronized environment variable: $clean_name"
done < "$TEMP_PARAMS"

# Clean up
rm -f "$TEMP_PARAMS"

# Append static container environment hooks required by Docker Compose
echo "" >> $ENV_FILE
echo "# --- Static Service Host Configuration ---" >> $ENV_FILE
echo "POSTGRES_HOST=postgres" >> $ENV_FILE
echo "POSTGRES_PORT=5432" >> $ENV_FILE
echo "REDIS_HOST=redis" >> $ENV_FILE
echo "REDIS_PORT=6379" >> $ENV_FILE
echo "NATS_URL=nats://nats:4222" >> $ENV_FILE
echo "IDENTITY_GRPC_HOST=identity-service" >> $ENV_FILE
echo "MESSAGING_GRPC_HOST=messaging-service" >> $ENV_FILE

echo "------------------------------------------------------------"
echo "🚀 Environment Variable Sync Complete!"
echo "📄 Created: $ENV_FILE ($(wc -l < $ENV_FILE) lines)"
echo "------------------------------------------------------------"
chmod 600 $ENV_FILE
